// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyClone.Playlists.Infrastructure.Persistence.Database;

#nullable disable

namespace SpotifyClone.Playlists.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlaylistsAppDbContext))]
    [Migration("20260406150336_Playlists_Add_CreatedAtUtc_Property")]
    partial class Playlists_Add_CreatedAtUtc_Property
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("playlists")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotifyClone.Playlists.Domain.Aggregates.Playlists.Entities.PlaylistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("Id", "PlaylistId")
                        .IsUnique();

                    b.HasIndex("PlaylistId", "Position")
                        .IsUnique();

                    b.ToTable("playlist_tracks", "playlists");
                });

            modelBuilder.Entity("SpotifyClone.Playlists.Domain.Aggregates.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("playlists", "playlists");
                });

            modelBuilder.Entity("SpotifyClone.Playlists.Infrastructure.Persistence.Entities.TrackReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_image_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("track_references", "playlists");
                });

            modelBuilder.Entity("SpotifyClone.Playlists.Infrastructure.Persistence.Entities.UserReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("user_references", "playlists");
                });

            modelBuilder.Entity("SpotifyClone.Shared.BuildingBlocks.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occured_on");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("outbox_messages", "playlists");
                });

            modelBuilder.Entity("SpotifyClone.Playlists.Domain.Aggregates.Playlists.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("SpotifyClone.Playlists.Domain.Aggregates.Playlists.Playlist", null)
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyClone.Playlists.Domain.Aggregates.Playlists.Playlist", b =>
                {
                    b.OwnsOne("SpotifyClone.Playlists.Domain.Aggregates.Playlists.ValueObjects.PlaylistCoverImage", "Cover", b1 =>
                        {
                            b1.Property<Guid>("PlaylistId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("cover_image_id");

                            b1.HasKey("PlaylistId");

                            b1.ToTable("playlists", "playlists");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("PlaylistCoverImagePlaylistId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cover_metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("cover_metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_width");

                                    b2.HasKey("PlaylistCoverImagePlaylistId");

                                    b2.ToTable("playlists", "playlists");

                                    b2.WithOwner()
                                        .HasForeignKey("PlaylistCoverImagePlaylistId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.OwnsMany("SpotifyClone.Shared.Kernel.IDs.UserId", "Collaborators", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("PlaylistId")
                                .HasColumnType("uuid")
                                .HasColumnName("playlist_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("collaborator_id");

                            b1.HasKey("Id");

                            b1.HasIndex("PlaylistId", "Value")
                                .IsUnique();

                            b1.ToTable("playlist_collaborators", "playlists");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");
                        });

                    b.Navigation("Collaborators");

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("SpotifyClone.Playlists.Domain.Aggregates.Playlists.Playlist", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
