// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyClone.Catalog.Infrastructure.Persistence.Database;

#nullable disable

namespace SpotifyClone.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogAppDbContext))]
    [Migration("20260406150238_Catalog_Add_CreatedAtUtc_Property")]
    partial class Catalog_Add_CreatedAtUtc_Property
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Albums.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("albums", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Albums.Entities.AlbumTrack", b =>
                {
                    b.Property<Guid>("album_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("album_id", "Id");

                    b.HasIndex("Id", "album_id")
                        .IsUnique();

                    b.HasIndex("Id", "Position", "album_id")
                        .IsUnique();

                    b.ToTable("album_tracks", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Artists.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("artists", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Genres.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genres", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Moods.Mood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("moods", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Tracks.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid?>("AudioFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_file_id");

                    b.Property<bool>("ContainsExplicitContent")
                        .HasColumnType("boolean")
                        .HasColumnName("contains_explicit_content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("AudioFileId")
                        .IsUnique();

                    b.ToTable("tracks", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Shared.BuildingBlocks.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occured_on");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Albums.Album", b =>
                {
                    b.OwnsMany("SpotifyClone.Catalog.Domain.Aggregates.Artists.ValueObjects.ArtistId", "MainArtists", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AlbumId")
                                .HasColumnType("uuid")
                                .HasColumnName("album_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("artist_id");

                            b1.HasKey("Id");

                            b1.HasIndex("AlbumId", "Value")
                                .IsUnique();

                            b1.ToTable("album_main_artists", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");
                        });

                    b.OwnsOne("SpotifyClone.Catalog.Domain.Aggregates.Albums.ValueObjects.AlbumCoverImage", "Cover", b1 =>
                        {
                            b1.Property<Guid>("AlbumId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("cover_image_id");

                            b1.HasKey("AlbumId");

                            b1.ToTable("albums", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("AlbumCoverImageAlbumId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cover_metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("cover_metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_width");

                                    b2.HasKey("AlbumCoverImageAlbumId");

                                    b2.ToTable("albums", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("AlbumCoverImageAlbumId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.Navigation("Cover");

                    b.Navigation("MainArtists");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Albums.Entities.AlbumTrack", b =>
                {
                    b.HasOne("SpotifyClone.Catalog.Domain.Aggregates.Albums.Album", null)
                        .WithMany("Tracks")
                        .HasForeignKey("album_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Artists.Artist", b =>
                {
                    b.OwnsOne("SpotifyClone.Catalog.Domain.Aggregates.Artists.ValueObjects.ArtistAvatarImage", "Avatar", b1 =>
                        {
                            b1.Property<Guid>("ArtistId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("avatar_image_id");

                            b1.HasKey("ArtistId");

                            b1.ToTable("artists", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("ArtistAvatarImageArtistId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("avatar_metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("avatar_metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("avatar_metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("avatar_metadata_width");

                                    b2.HasKey("ArtistAvatarImageArtistId");

                                    b2.ToTable("artists", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ArtistAvatarImageArtistId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.OwnsOne("SpotifyClone.Catalog.Domain.Aggregates.Artists.ValueObjects.ArtistBannerImage", "Banner", b1 =>
                        {
                            b1.Property<Guid>("ArtistId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("banner_image_id");

                            b1.HasKey("ArtistId");

                            b1.ToTable("artists", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("ArtistBannerImageArtistId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .HasColumnType("text")
                                        .HasColumnName("banner_metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("banner_metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("banner_metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("banner_metadata_width");

                                    b2.HasKey("ArtistBannerImageArtistId");

                                    b2.ToTable("artists", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ArtistBannerImageArtistId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.OwnsMany("SpotifyClone.Catalog.Domain.Aggregates.Artists.ValueObjects.ArtistGalleryImage", "Gallery", b1 =>
                        {
                            b1.Property<Guid>("ArtistId")
                                .HasColumnType("uuid")
                                .HasColumnName("artist_id");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("image_id");

                            b1.HasKey("ArtistId", "ImageId");

                            b1.ToTable("artist_gallery_images", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("ArtistGalleryImageArtistId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ArtistGalleryImageImageId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("metadata_width");

                                    b2.HasKey("ArtistGalleryImageArtistId", "ArtistGalleryImageImageId");

                                    b2.ToTable("artist_gallery_images", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ArtistGalleryImageArtistId", "ArtistGalleryImageImageId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.Navigation("Avatar");

                    b.Navigation("Banner");

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Genres.Genre", b =>
                {
                    b.OwnsOne("SpotifyClone.Catalog.Domain.Aggregates.Genres.ValueObjects.GenreCoverImage", "Cover", b1 =>
                        {
                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("cover_image_id");

                            b1.HasKey("GenreId");

                            b1.ToTable("genres", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("GenreId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("GenreCoverImageGenreId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cover_metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("cover_metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_width");

                                    b2.HasKey("GenreCoverImageGenreId");

                                    b2.ToTable("genres", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("GenreCoverImageGenreId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Moods.Mood", b =>
                {
                    b.OwnsOne("SpotifyClone.Catalog.Domain.Aggregates.Moods.ValueObjects.MoodCoverImage", "Cover", b1 =>
                        {
                            b1.Property<Guid>("MoodId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("cover_image_id");

                            b1.HasKey("MoodId");

                            b1.ToTable("moods", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("MoodId");

                            b1.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("MoodCoverImageMoodId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileType")
                                        .HasColumnType("text")
                                        .HasColumnName("cover_metadata_file_type");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_height");

                                    b2.Property<long>("SizeInBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("cover_metadata_size_in_bytes");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer")
                                        .HasColumnName("cover_metadata_width");

                                    b2.HasKey("MoodCoverImageMoodId");

                                    b2.ToTable("moods", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("MoodCoverImageMoodId");
                                });

                            b1.Navigation("Metadata")
                                .IsRequired();
                        });

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Tracks.Track", b =>
                {
                    b.OwnsMany("SpotifyClone.Catalog.Domain.Aggregates.Genres.ValueObjects.GenreId", "Genres", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("genre_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TrackId", "Value")
                                .IsUnique();

                            b1.ToTable("track_genres", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsMany("SpotifyClone.Catalog.Domain.Aggregates.Moods.ValueObjects.MoodId", "Moods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("mood_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TrackId", "Value")
                                .IsUnique();

                            b1.ToTable("track_moods", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsMany("SpotifyClone.Catalog.Domain.Aggregates.Artists.ValueObjects.ArtistId", "FeaturedArtists", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("artist_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TrackId", "Value")
                                .IsUnique();

                            b1.ToTable("track_featured_artists", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsMany("SpotifyClone.Catalog.Domain.Aggregates.Artists.ValueObjects.ArtistId", "MainArtists", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("artist_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TrackId", "Value")
                                .IsUnique();

                            b1.ToTable("track_main_artists", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("FeaturedArtists");

                    b.Navigation("Genres");

                    b.Navigation("MainArtists");

                    b.Navigation("Moods");
                });

            modelBuilder.Entity("SpotifyClone.Catalog.Domain.Aggregates.Albums.Album", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
