// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyClone.Billing.Infrastructure.Persistence.Database;

#nullable disable

namespace SpotifyClone.Billing.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BillingAppDbContext))]
partial class BillingAppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("billing")
            .HasAnnotation("ProductVersion", "10.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SpotifyClone.Billing.Domain.Aggregates.Subscriptions.Subscription", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<bool>("CancelAtPeriodEnd")
                    .HasColumnType("boolean")
                    .HasColumnName("cancel_at_period_end");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("current_period_end");

                b.Property<DateTimeOffset?>("CurrentPeriodStart")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("current_period_start");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id");

                b.ToTable("subscriptions", "billing");
            });

        modelBuilder.Entity("SpotifyClone.Shared.BuildingBlocks.Application.Outbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("content");

                b.Property<string>("Error")
                    .HasColumnType("text")
                    .HasColumnName("error");

                b.Property<DateTimeOffset>("OccurredOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occured_on");

                b.Property<DateTimeOffset?>("ProcessedOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_on");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("type");

                b.HasKey("Id");

                b.HasIndex("ProcessedOn");

                b.ToTable("outbox_messages", "billing");
            });

        modelBuilder.Entity("SpotifyClone.Billing.Domain.Aggregates.Subscriptions.Subscription", b =>
            {
                b.OwnsOne("SpotifyClone.Billing.Domain.Aggregates.Subscriptions.ValueObjects.PaymentProviderIdentity", "ExternalIdentity", b1 =>
                    {
                        b1.Property<Guid>("SubscriptionId1")
                            .HasColumnType("uuid");

                        b1.Property<string>("CustomerId")
                            .IsRequired()
                            .HasColumnType("text")
                            .HasColumnName("external_customer_id");

                        b1.Property<string>("SubscriptionId")
                            .HasColumnType("text")
                            .HasColumnName("external_subscription_id");

                        b1.HasKey("SubscriptionId1");

                        b1.ToTable("subscriptions", "billing");

                        b1.WithOwner()
                            .HasForeignKey("SubscriptionId1");
                    });

                b.Navigation("ExternalIdentity")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
